-- Usar Database
USE SuperLorenz;

INSERT INTO Producto (ProductoID, NombreDelProducto, DescripcionDelProducto, Categoria, Marca)
VALUES
(5008, 'Papas Fritas', 'Papas fritas clásicas en bolsa de 150g', 'Snacks', 'Margarita'),
(5009, 'Jugo de Naranja', 'Jugo de naranja natural en botella de 500ml', 'Bebidas', 'Del Valle'),
(5010, 'Pan Integral', 'Pan integral en bolsa de 500g', 'Panadería', 'Bimbo'),
(5011, 'Yogur Natural', 'Yogur natural sin azúcar, 1L', 'Lácteos', 'Alpina'),
(5012, 'Galletas de Chocolate', 'Galletas de chocolate rellenas, paquete de 200g', 'Snacks', 'Noel'),
(5013, 'Aceite de Oliva', 'Aceite de oliva extra virgen, 500ml', 'Aceites', 'La Española'),
(5014, 'Salsa de Tomate', 'Salsa de tomate clásica, 250g', 'Condimentos', 'Heinz'),
(5015, 'Harina de Trigo', 'Harina de trigo refinada, bolsa de 1kg', 'Cereales', 'Colanta'),
(5016, 'Azúcar Morena', 'Azúcar morena sin refinar, bolsa de 1kg', 'Endulzantes', 'Incauca'),
(5017, 'Queso Mozzarella', 'Queso mozzarella rallado, 500g', 'Lácteos', 'Colanta'),
(5018, 'Jamón de Pavo', 'Jamón de pavo en lonchas, 250g', 'Embutidos', 'Zenú'),
(5019, 'Agua Mineral', 'Agua mineral con gas, botella de 600ml', 'Bebidas', 'Perrier'),
(5020, 'Mantequilla', 'Mantequilla con sal, 250g', 'Lácteos', 'Alquería'),
(5021, 'Café Molido', 'Café molido 100% colombiano, 500g', 'Bebidas', 'Juan Valdez'),
(5022, 'Te Negro', 'Té negro en bolsitas, paquete de 100g', 'Bebidas', 'Lipton'),
(5023, 'Salchichas de Pollo', 'Salchichas de pollo, paquete de 500g', 'Embutidos', 'Zenú'),
(5024, 'Cereal de Maíz', 'Cereal de maíz crocante, 500g', 'Cereales', 'Kelloggs'),
(5025, 'Chocolate en Polvo', 'Chocolate en polvo para bebida, 500g', 'Bebidas', 'Nesquik'),
(5026, 'Lentejas', 'Lentejas secas en bolsa de 500g', 'Legumbres', 'Diana'),
(5027, 'Atún en Lata', 'Atún en lata con aceite, 170g', 'Pescados', 'Van Camps'),
(5028, 'Helado de Vainilla', 'Helado de vainilla en pote de 1L', 'Postres', 'Cremeria Italiana'),
(5029, 'Coco Rallado', 'Coco rallado en bolsa de 200g', 'Repostería', 'El Rey'),
(5030, 'Galletas de Soda', 'Galletas de soda en paquete de 400g', 'Panadería', 'Saltín Noel'),
(5031, 'Maicena', 'Maicena en caja de 200g', 'Repostería', 'Maizena'),
(5032, 'Frijoles Rojos', 'Frijoles rojos secos en bolsa de 500g', 'Legumbres', 'Diana'),
(5033, 'Papel Higiénico', 'Papel higiénico en paquete de 12 rollos', 'Aseo Personal', 'Familia'),
(5034, 'Jabón Líquido', 'Jabón líquido para manos, 250ml', 'Aseo Personal', 'Protex'),
(5035, 'Desodorante en Spray', 'Desodorante en spray para hombre, 150ml', 'Aseo Personal', 'Axe'),
(5036, 'Pasta Dental', 'Pasta dental con flúor, 75ml', 'Aseo Personal', 'Colgate'),
(5037, 'Shampoo Anticaspa', 'Shampoo anticaspa, 400ml', 'Cuidado del Cabello', 'Head & Shoulders'),
(5038, 'Acondicionador de Cabello', 'Acondicionador para cabello seco, 400ml', 'Cuidado del Cabello', 'Pantene'),
(5039, 'Toallas Húmedas', 'Toallas húmedas para bebés, paquete de 80 unidades', 'Aseo Personal', 'Huggies'),
(5040, 'Jabón en Barra', 'Jabón en barra antibacterial, 125g', 'Aseo Personal', 'Dove'),
(5041, 'Limpiavidrios', 'Limpiavidrios en spray, 500ml', 'Limpieza', 'Windex'),
(5042, 'Cloro', 'Cloro concentrado para limpieza, 1L', 'Limpieza', 'Clorox'),
(5043, 'Cera para Pisos', 'Cera para pisos de madera, 500ml', 'Limpieza', 'Brillax'),
(5044, 'Esponjas de Cocina', 'Esponjas de cocina, paquete de 3 unidades', 'Limpieza', 'Scotch-Brite'),
(5045, 'Desinfectante', 'Desinfectante multisuperficies, 1L', 'Limpieza', 'Lysol'),
(5046, 'Leche Descremada', 'Leche descremada en botella de 1L', 'Lácteos', 'Alquería'),
(5047, 'Huevos', 'Huevos frescos en cartón de 30 unidades', 'Huevos', 'Kikes'),
(5048, 'Miel de Abeja', 'Miel de abeja natural, 500g', 'Endulzantes', 'Apicola'),
(5049, 'Mermelada de Fresa', 'Mermelada de fresa, 300g', 'Repostería', 'La Constancia'),
(5050, 'Vinagre de Manzana', 'Vinagre de manzana orgánico, 500ml', 'Condimentos', 'Bragg');